//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hungermidterm.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collectfood
    {
        public int Id { get; set; }
        public int Request_no { get; set; }
        public string Dish_name { get; set; }
        public string Type { get; set; }
        public string Quantity { get; set; }
        public string pick_date { get; set; }
    }
}
