//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hungermidterm.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public int Resid { get; set; }
        public string Resname { get; set; }
        public string Email { get; set; }
        public string phone { get; set; }
        public string Address { get; set; }
    }
}
